#!/bin/bash

clear
#Проверка пользователя на root права
if [ "$(id -u)" != 0 ]
then 
	echo "root permission required" && echo ""
	exit 1
fi

clear

# Установка репозитория Oracle MySQL 8.0

echo ""
echo "Устанавливаем репозиторий MySQL"
echo ""
sleep 3
rpm -Uvh https://repo.mysql.com/mysql80-community-release-el7-6.noarch.rpm
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

# Включаем репозиторий
sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/mysql-community.repo
sleep 3
clear

echo ""
echo "Устанавливаем MySQL"
echo ""
sleep 3
# Устанавливаем MySQL
yum --enablerepo=mysql80-community install mysql-community-server -y
sleep 3
clear
echo ""
echo "Запускаем MySQL"
echo ""

# Запускаем
systemctl start mysqld && systemctl enable mysqld

# Отключаем firewalld
systemctl stop firewalld
systemctl disable firewalld

# Проверка портов
ss -ntlp | grep mysql
sleep 5

# Выберем название нашего сервера
echo ""
echo -e $'\e[1;32m\e[0m\e[1;32mНа какой сервер выполняется установка MySQL? \e[0m'
echo ""

printf "\e[1;32m[\e[0m\e[1;77m1\e[0m\e[1;32m]\e[0m\e[1;93m Master             \e[1;92m[\e[0m\e[1;77m0\e[0m\e[1;92m]\e[0m\e[1;93m Выход         \n"                                                                       
printf "\e[1;92m[\e[0m\e[1;77m2\e[0m\e[1;92m]\e[0m\e[1;93m Slave			\e[0m           \e[0m\n"                                                                                                                                                                                                                                                                                                    
echo ""
                
read -p $'\e[1;33m[\e[0m\e[1;77m+\e[0m\e[1;33m]\e[0m\e[1;32m Введите ваш выбор : \e[0m' option
case $option in 
			 
            1)hostnamectl set-hostname mysql-Master && echo "Временный пароль" && grep "A temporary password" /var/log/mysqld.log && mysql_secure_installation && echo "Заходим с паролем: mysql -uroot -p"
            exit
            ;;

			2)hostnamectl set-hostname mysql-Slave && echo "Временный пароль" && grep "A temporary password" /var/log/mysqld.log && mysql_secure_installation && echo "Заходим с паролем: mysql -uroot -p"
			exit
            ;;
			
            0)clear && exit
			exit
            ;;
			esac
                ;;
