#!/bin/bash

clear
#Проверка пользователя на root права
if [ "$(id -u)" != 0 ]
then 
	echo "root permission required" && echo ""
	exit 1
fi

echo ""
echo "Начинаем установку обновления системы…"
sleep 5
yum -y update
sleep 5
clear
echo ""
echo "Начинаем установку Nginx"
sleep 5
yum -y install epel-release && yum -y install nginx && systemctl stop firewalld && systemctl disable firewalld
sleep 5
clear
echo ""
echo "Копирование конфигурационных файлов…"
echo ""
mkdir /etc/nginx/conf.d/ && mkdir /etc/nginx/default.d/
mv -fv nginx.conf /etc/nginx/ && mv -fv nginxbalance.conf /etc/nginx/conf.d/ && nginx -t
echo ""
echo "Запуск Nginx"
echo ""
systemctl start nginx && systemctl enable nginx && systemctl status nginx && systemctl reload nginx
sleep 5
echo "Установка Nginx завершена"
echo ""
