#!/bin/bash

clear
#Проверка пользователя на root права
if [ "$(id -u)" != 0 ]
then 
	echo "root permission required" && echo ""
	exit 1
fi

echo ""
echo "Установка зависимости Java jdk"
echo ""
sleep 3
yum install -y epel-release
yum install -y java-openjdk-devel java-openjdk
clear
echo ""
echo "Скачиваем пакеты filebeat elasticsearch kibana logstash"
echo ""
sleep 3

# filebeat_7.17.3_x86_64-224190-4c3205.rpm
wget http://192.168.49.128/filebeat_7.17.3_x86_64-224190-4c3205.rpm

# elasticsearch_7.17.3_x86_64-224190-9bcb26.rpm
wget http://192.168.49.128/elasticsearch_7.17.3_x86_64-224190-9bcb26.rpm

# kibana_7.17.3_x86_64-224190-b13e53.rpm
wget http://192.168.49.128/kibana_7.17.3_x86_64-224190-b13e53.rpm

# logstash_7.17.3_x86_64-224190-3a605f.rpm
wget http://192.168.49.128/logstash_7.17.3_x86_64-224190-3a605f.rpm

clear
echo ""
echo "Устанавливаем пакеты filebeat elasticsearch kibana logstash"
echo ""
sleep 3
rpm -i ./*.rpm
clear
echo ""
echo "Установка filebeat elasticsearch kibana logstash завершена"
echo ""
sleep 3
clear
echo ""
echo "Копирование конфигурационных файлов"
echo ""
mv -fv ./jvm.options /etc/elasticsearch/jvm.options.d/

# Запускаем сервис elasticsearch
systemctl enable --now elasticsearch.service

# Проверяем
curl http://127.0.0.1:9200

mv -fv ./kibana.yml /etc/kibana/

# Запускаем сервис kibana
sudo systemctl enable --now kibana

# Редактируем logstash config
mv -fv ./logstash.yml /etc/logstash/

# Настраиваем обработчик логов от nginx'a
mv -fv ./logstash-nginx-es.conf /etc/logstash/conf.d/

# Restart logstash
systemctl restart logstash.service

# Редактируем конфиг filebeat
mv -fv ./filebeat.yml /etc/filebeat/

# Запускаем и перезагружаем сервис filebeat
systemctl enable filebeat
systemctl restart filebeat

sleep 3
clear
echo ""
echo "Копирование конфигурационных файлов завершено"
echo ""
echo "Заходим в панель IP:5601 (Discover-->create index pattern-->name: weblogs*) и настраиваем визуализацию"
echo ""
