#!/bin/bash

clear
#Проверка пользователя на root права
if [ "$(id -u)" != 0 ]
then 
	echo "root permission required" && echo ""
	exit 1
fi

echo ""
echo "Начинаем установку Apache..."
echo ""
sleep 5
yum update httpd && yum -y install httpd && systemctl stop firewalld && systemctl disable firewalld
clear
echo ""
echo "Установка Apache завершена"
echo ""
sleep 5
clear
echo ""
echo "Копирование конфигурационных файлов…"
echo ""
sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf && mv -fv apachebalance.conf /etc/httpd/conf.d/ && mkdir /var/www/html /var/www/html1 /var/www/html2
echo "<html>Folder HTML, Apache backend</html>" > /var/www/html/index.html && echo "<html>Folder HTML 1, Apache backend</html>" > /var/www/html1/index.html
echo "<html>Folder HTML 2, Apache backend</html>" > /var/www/html2/index.html
echo ""
echo "Копирование конфигурационных файлов завершено"
echo ""
echo "Apache backend working on ports 8080, 8081, 8082"
echo ""
sleep 5
echo ""
echo "Запускаем службу Apache"
echo ""
systemctl enable httpd && systemctl start httpd && apachectl -t && systemctl reload httpd && systemctl status httpd
