#!/bin/bash

clear
#Проверка пользователя на root права
if [ "$(id -u)" != 0 ]
then 
	echo "root permission required" && echo ""
	exit 1
fi

echo ""
echo "Скачиваем и начинаем установку Prometheus, Nodeexporter"
echo ""
sleep 3
wget https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz
wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz

# Unzip files
tar -xf prometheus-2.37.0.linux-amd64.tar.gz
tar -xf node_exporter-1.3.1.linux-amd64.tar.gz

# Create users
useradd --no-create-home --shell /usr/sbin/nologin prometheus
useradd --no-create-home --shell /bin/false node_exporter

# Create dir
mkdir {/etc/,/var/lib/}prometheus

# Copy files
cp -rv ./prometheus-2.37.0.linux-amd64/consoles ./prometheus-2.37.0.linux-amd64/console_libraries ./prometheus-2.37.0.linux-amd64/prometheus.yml /etc/prometheus/
cp -rv ./prometheus-2.37.0.linux-amd64/prometheus ./prometheus-2.37.0.linux-amd64/promtool /usr/local/bin/
cp -rv ./node_exporter-1.3.1.linux-amd64/node_exporter /usr/local/bin/

# Change owners folders
chown -vR prometheus: /etc/prometheus/ /var/lib/prometheus/ /usr/local/bin/prom*
chown -vR node_exporter: /usr/local/bin/node_exporter

# Create files in /etc/systemd/system
mv -fv ./prometheus.service /etc/systemd/system
mv -fv ./node_exporter.service /etc/systemd/system
systemctl daemon-reload
systemctl enable --now node_exporter.service && systemctl enable --now prometheus.service

# Addd job_name to config file prometheus /etc/prometheus/prometheus.yml
mv -fv ./prometheus.yml /etc/prometheus/
systemctl reload prometheus.service

clear
echo ""
echo "Скачиваем и начинаем установку Grafana"
echo ""
sleep 3
# Install Grafana
wget https://dl.grafana.com/oss/release/grafana-9.1.0-1.x86_64.rpm
yum install -y grafana-9.1.0-1.x86_64.rpm

# Start and add autostart Grafana
systemctl enable --now grafana-server.service

clear
echo ""
echo "Установка Prometheus node_exporter Grafana завершена"
echo ""
echo "Посетите страницу IP:3000 admin:admin"
echo ""
echo "P.S. Node Exporter dashboard ID: 1860"
echo ""
